version: '3.8'

services:
  frontend:
    container_name: AetherNet-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=
    depends_on:
      - backend
    networks:
      - aethernet-network

networks:
  aethernet-network:
    driver: bridge